### PR TITLE
index.html

### PR DESCRIPTION
**Pull request by sanskarmalkhede**
Added a image in the website for more professional look.

### CODE REVIEW

**Comment by JUSTADI16** [comment]
There's no need for an image

**Comment by sanskarmalkhede** [comment]
kar leta bc accept tera kya jara waise bhi teri fake profile hai

**Comment by JUSTADI16** [comment]
Chal chutiye

**Comment by sanskarmalkhede** [comment]
bhag sala spammer

**Comment by JUSTADI16** [comment]
Apna dekh bhadve

**Comment by sanskarmalkhede** [comment]
chal na chutiye fake id banake krra khud hi aur dusro ko galiya bakra
bhadvi ka

**Comment by JUSTADI16** [comment]
Thik hai na bhai
Teri gand me khujli kyu horhi hai 😂😂

**Pull request closed without merging**
